name: cherry-picker-on-comment

on:
  issues:
    types: [milestoned]

env:
  GH_TOKEN: ${{ secrets.BAZEL_IO_TOKEN }}

jobs:
  cherry-picker-on-comment:
    if: startsWith(github.event.issue.body, 'Forked from')
    runs-on: ubuntu-latest
    steps:
      - name: Run cherrypicker on comment
        uses: bazelbuild/continuous-integration/actions/cherry-picker@master
        with:
          triggered-on: commented
          pr-number: ${{ github.event.issue.body }}
          milestone-title: ${{ github.event.milestone.title }}
          milestoned-issue-number: ${{ github.event.issue.number }}
          is-prod: True
